// <auto-generated />
using DepartApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepartApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("DepartApi.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Inovação Tecnológica",
                            Sigla = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Recursos Humano",
                            Sigla = "RH"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Financeiro",
                            Sigla = "FIN"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Marketing",
                            Sigla = "MK"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Desenvolvimento de Software",
                            Sigla = "DEV"
                        });
                });

            modelBuilder.Entity("DepartApi.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 5,
                            Foto = "https://picsum.photos/100/100",
                            Nome = "Miguel",
                            RG = "987654321"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 1,
                            Foto = "https://picsum.photos/100/100",
                            Nome = "Heloisa",
                            RG = "123456789"
                        },
                        new
                        {
                            Id = 3,
                            DepartamentoId = 2,
                            Foto = "https://picsum.photos/100/100",
                            Nome = "Mariana",
                            RG = "916782345"
                        },
                        new
                        {
                            Id = 4,
                            DepartamentoId = 4,
                            Foto = "https://picsum.photos/100/100",
                            Nome = "Lucas",
                            RG = "456237891"
                        },
                        new
                        {
                            Id = 5,
                            DepartamentoId = 3,
                            Foto = "https://picsum.photos/100/100",
                            Nome = "Luis",
                            RG = "912345678"
                        });
                });

            modelBuilder.Entity("DepartApi.Models.Funcionario", b =>
                {
                    b.HasOne("DepartApi.Models.Departamento", null)
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DepartApi.Models.Departamento", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
